config/routes.rb
Fantasy::Application.routes.draw do
  resources :box_scores
  resources :box_score_entries
end

app/models/box_score.rb
class BoxScore < ActiveRecord::Base
  has_many :box_score_entries, :dependent => :destroy

  # TODO add validations
end

app/models/box_score_entry.rb
class BoxScoreEntry < ActiveRecord::Base
  belongs_to :box_score

  # TODO add validations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/box_score_entries_controller.rb
class BoxScoreEntriesController < ApplicationController
  before_action :set_box_score_entry, only: [:show, :edit, :update, :destroy]

  # GET /box_score_entries
  # GET /box_score_entries.json
  def index
    @box_score_entries = BoxScoreEntry.all
  end

  # GET /box_score_entries/1
  # GET /box_score_entries/1.json
  def show
  end

  # GET /box_score_entries/new
  def new
    @box_score_entry = BoxScoreEntry.new
  end

  # GET /box_score_entries/1/edit
  def edit
  end

  # POST /box_score_entries
  # POST /box_score_entries.json
  def create
    @box_score_entry = BoxScoreEntry.new(box_score_entry_params)

    respond_to do |format|
      if @box_score_entry.save
        format.html { redirect_to @box_score_entry, notice: 'Box score entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @box_score_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @box_score_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /box_score_entries/1
  # PATCH/PUT /box_score_entries/1.json
  def update
    respond_to do |format|
      if @box_score_entry.update(box_score_entry_params)
        format.html { redirect_to @box_score_entry, notice: 'Box score entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @box_score_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /box_score_entries/1
  # DELETE /box_score_entries/1.json
  def destroy
    @box_score_entry.destroy
    respond_to do |format|
      format.html { redirect_to box_score_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box_score_entry
      @box_score_entry = BoxScoreEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_score_entry_params
      params.require(:box_score_entry).permit(:box_score_id, :pid_espn, :fname, :lname, :status, :min, :fgm, :fga, :tpm, :tpa, :ftm, :fta, :oreb, :reb, :ast, :stl, :blk, :to, :pf, :plus_minus, :pts)
    end
end

app/controllers/box_scores_controller.rb
class BoxScoresController < ApplicationController
  before_action :set_box_score, only: [:show, :edit, :update, :destroy]

  # GET /box_scores
  # GET /box_scores.json
  def index
    @box_scores = BoxScore.all
  end

  # GET /box_scores/1
  # GET /box_scores/1.json
  def show
  end

  # GET /box_scores/new
  def new
    @box_score = BoxScore.new
  end

  # GET /box_scores/1/edit
  def edit
  end

  # POST /box_scores
  # POST /box_scores.json
  def create
    @box_score = BoxScore.new(box_score_params)

    respond_to do |format|
      if @box_score.save
        format.html { redirect_to @box_score, notice: 'Box score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @box_score }
      else
        format.html { render action: 'new' }
        format.json { render json: @box_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /box_scores/1
  # PATCH/PUT /box_scores/1.json
  def update
    respond_to do |format|
      if @box_score.update(box_score_params)
        format.html { redirect_to @box_score, notice: 'Box score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @box_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /box_scores/1
  # DELETE /box_scores/1.json
  def destroy
    @box_score.destroy
    respond_to do |format|
      format.html { redirect_to box_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box_score
      @box_score = BoxScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_score_params
      params.require(:box_score).permit(:gid_espn, :status, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_score_entries_helper.rb
module BoxScoreEntriesHelper
end

app/helpers/box_scores_helper.rb
module BoxScoresHelper
end

app/views/box_score_entries/_form.html.erb
<%= form_for(@box_score_entry) do |f| %>
  <% if @box_score_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box_score_entry.errors.count, "error") %> prohibited this box_score_entry from being saved:</h2>

      <ul>
      <% @box_score_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :box_score_id %><br>
    <%= f.number_field :box_score_id %>
  </div>
  <div class="field">
    <%= f.label :pid_espn %><br>
    <%= f.number_field :pid_espn %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :min %><br>
    <%= f.number_field :min %>
  </div>
  <div class="field">
    <%= f.label :fgm %><br>
    <%= f.number_field :fgm %>
  </div>
  <div class="field">
    <%= f.label :fga %><br>
    <%= f.number_field :fga %>
  </div>
  <div class="field">
    <%= f.label :tpm %><br>
    <%= f.number_field :tpm %>
  </div>
  <div class="field">
    <%= f.label :tpa %><br>
    <%= f.number_field :tpa %>
  </div>
  <div class="field">
    <%= f.label :ftm %><br>
    <%= f.number_field :ftm %>
  </div>
  <div class="field">
    <%= f.label :fta %><br>
    <%= f.number_field :fta %>
  </div>
  <div class="field">
    <%= f.label :oreb %><br>
    <%= f.number_field :oreb %>
  </div>
  <div class="field">
    <%= f.label :reb %><br>
    <%= f.number_field :reb %>
  </div>
  <div class="field">
    <%= f.label :ast %><br>
    <%= f.number_field :ast %>
  </div>
  <div class="field">
    <%= f.label :stl %><br>
    <%= f.number_field :stl %>
  </div>
  <div class="field">
    <%= f.label :blk %><br>
    <%= f.number_field :blk %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.number_field :to %>
  </div>
  <div class="field">
    <%= f.label :pf %><br>
    <%= f.number_field :pf %>
  </div>
  <div class="field">
    <%= f.label :plus_minus %><br>
    <%= f.number_field :plus_minus %>
  </div>
  <div class="field">
    <%= f.label :pts %><br>
    <%= f.number_field :pts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/box_score_entries/edit.html.erb
<h1>Editing box_score_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @box_score_entry %> |
<%= link_to 'Back', box_score_entries_path %>

app/views/box_score_entries/index.html.erb
<h1>Listing box_score_entries</h1>

<table>
  <thead>
    <tr>
      <th>Box score id</th>
      <th>Pid espn</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Status</th>
      <th>Min</th>
      <th>Fgm</th>
      <th>Fga</th>
      <th>Tpm</th>
      <th>Tpa</th>
      <th>Ftm</th>
      <th>Fta</th>
      <th>Oreb</th>
      <th>Reb</th>
      <th>Ast</th>
      <th>Stl</th>
      <th>Blk</th>
      <th>To</th>
      <th>Pf</th>
      <th>Plus minus</th>
      <th>Pts</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @box_score_entries.each do |box_score_entry| %>
      <tr>
        <td><%= box_score_entry.box_score_id %></td>
        <td><%= box_score_entry.pid_espn %></td>
        <td><%= box_score_entry.fname %></td>
        <td><%= box_score_entry.lname %></td>
        <td><%= box_score_entry.status %></td>
        <td><%= box_score_entry.min %></td>
        <td><%= box_score_entry.fgm %></td>
        <td><%= box_score_entry.fga %></td>
        <td><%= box_score_entry.tpm %></td>
        <td><%= box_score_entry.tpa %></td>
        <td><%= box_score_entry.ftm %></td>
        <td><%= box_score_entry.fta %></td>
        <td><%= box_score_entry.oreb %></td>
        <td><%= box_score_entry.reb %></td>
        <td><%= box_score_entry.ast %></td>
        <td><%= box_score_entry.stl %></td>
        <td><%= box_score_entry.blk %></td>
        <td><%= box_score_entry.to %></td>
        <td><%= box_score_entry.pf %></td>
        <td><%= box_score_entry.plus_minus %></td>
        <td><%= box_score_entry.pts %></td>
        <td><%= link_to 'Show', box_score_entry %></td>
        <td><%= link_to 'Edit', edit_box_score_entry_path(box_score_entry) %></td>
        <td><%= link_to 'Destroy', box_score_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box score entry', new_box_score_entry_path %>

app/views/box_score_entries/new.html.erb
<h1>New box_score_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', box_score_entries_path %>

app/views/box_score_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Box score id:</strong>
  <%= @box_score_entry.box_score_id %>
</p>

<p>
  <strong>Pid espn:</strong>
  <%= @box_score_entry.pid_espn %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @box_score_entry.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @box_score_entry.lname %>
</p>

<p>
  <strong>Status:</strong>
  <%= @box_score_entry.status %>
</p>

<p>
  <strong>Min:</strong>
  <%= @box_score_entry.min %>
</p>

<p>
  <strong>Fgm:</strong>
  <%= @box_score_entry.fgm %>
</p>

<p>
  <strong>Fga:</strong>
  <%= @box_score_entry.fga %>
</p>

<p>
  <strong>Tpm:</strong>
  <%= @box_score_entry.tpm %>
</p>

<p>
  <strong>Tpa:</strong>
  <%= @box_score_entry.tpa %>
</p>

<p>
  <strong>Ftm:</strong>
  <%= @box_score_entry.ftm %>
</p>

<p>
  <strong>Fta:</strong>
  <%= @box_score_entry.fta %>
</p>

<p>
  <strong>Oreb:</strong>
  <%= @box_score_entry.oreb %>
</p>

<p>
  <strong>Reb:</strong>
  <%= @box_score_entry.reb %>
</p>

<p>
  <strong>Ast:</strong>
  <%= @box_score_entry.ast %>
</p>

<p>
  <strong>Stl:</strong>
  <%= @box_score_entry.stl %>
</p>

<p>
  <strong>Blk:</strong>
  <%= @box_score_entry.blk %>
</p>

<p>
  <strong>To:</strong>
  <%= @box_score_entry.to %>
</p>

<p>
  <strong>Pf:</strong>
  <%= @box_score_entry.pf %>
</p>

<p>
  <strong>Plus minus:</strong>
  <%= @box_score_entry.plus_minus %>
</p>

<p>
  <strong>Pts:</strong>
  <%= @box_score_entry.pts %>
</p>

<%= link_to 'Edit', edit_box_score_entry_path(@box_score_entry) %> |
<%= link_to 'Back', box_score_entries_path %>

app/views/box_scores/_form.html.erb
<%= form_for(@box_score) do |f| %>
  <% if @box_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box_score.errors.count, "error") %> prohibited this box_score from being saved:</h2>

      <ul>
      <% @box_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gid_espn %><br>
    <%= f.number_field :gid_espn %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/box_scores/edit.html.erb
<h1>Editing box_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @box_score %> |
<%= link_to 'Back', box_scores_path %>

app/views/box_scores/index.html.erb
<h1>Listing box_scores</h1>

<table>
  <thead>
    <tr>
      <th>Gid espn</th>
      <th>Status</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @box_scores.each do |box_score| %>
      <tr>
        <td><%= box_score.gid_espn %></td>
        <td><%= box_score.status %></td>
        <td><%= box_score.date %></td>
        <td><%= link_to 'Show', box_score %></td>
        <td><%= link_to 'Edit', edit_box_score_path(box_score) %></td>
        <td><%= link_to 'Destroy', box_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box score', new_box_score_path %>

app/views/box_scores/new.html.erb
<h1>New box_score</h1>

<%= render 'form' %>

<%= link_to 'Back', box_scores_path %>

app/views/box_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gid espn:</strong>
  <%= @box_score.gid_espn %>
</p>

<p>
  <strong>Status:</strong>
  <%= @box_score.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @box_score.date %>
</p>

<%= link_to 'Edit', edit_box_score_path(@box_score) %> |
<%= link_to 'Back', box_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>